// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.yoursite.com/support",
            "email": "your.email@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check if the API is up and running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "API status and version",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search/{exerciseID}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Find an exercise using its ID without user context",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "Search for an exercise by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Exercise ID",
                        "name": "exerciseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exercise information",
                        "schema": {
                            "$ref": "#/definitions/store.Exercise"
                        }
                    },
                    "400": {
                        "description": "Invalid exercise ID format",
                        "schema": {}
                    },
                    "404": {
                        "description": "Exercise not found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to fetch exercise",
                        "schema": {}
                    }
                }
            }
        },
        "/user": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Register a new user in the system with username, email, and other basic information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User information including username, email, and password",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns the created user ID",
                        "schema": {}
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to create user",
                        "schema": {}
                    }
                }
            }
        },
        "/user/{userID}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a user's information by their ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User information",
                        "schema": {
                            "$ref": "#/definitions/store.User"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {}
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to fetch user",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Permanently remove a user from the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User was successfully deleted",
                        "schema": {}
                    },
                    "400": {
                        "description": "Invalid user ID format",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to delete user",
                        "schema": {}
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update one or more fields of a user's profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated user information",
                        "name": "userData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.updateUserPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User updated successfully",
                        "schema": {}
                    },
                    "400": {
                        "description": "Invalid request body or missing fields",
                        "schema": {}
                    },
                    "409": {
                        "description": "Version conflict - record has been modified",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to update user",
                        "schema": {}
                    }
                }
            }
        },
        "/users/{userID}/exercise": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve all exercises created by a specific user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "Get all exercises for a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of exercises",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.Exercise"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid user ID",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to fetch exercises",
                        "schema": {}
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a custom exercise for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "Create a new exercise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Exercise information",
                        "name": "exercise",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.Exercise"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Exercise created successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or missing required fields",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to create exercise",
                        "schema": {}
                    }
                }
            }
        },
        "/users/{userID}/exercise/{exerciseID}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a specific exercise by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "Get exercise by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exercise ID",
                        "name": "exerciseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exercise information",
                        "schema": {
                            "$ref": "#/definitions/store.Exercise"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {}
                    },
                    "404": {
                        "description": "Exercise not found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to fetch exercise",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove an exercise from the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "Delete an exercise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exercise ID",
                        "name": "exerciseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exercise successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to delete exercise",
                        "schema": {}
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update an existing exercise's details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exercises"
                ],
                "summary": "Update an exercise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exercise ID",
                        "name": "exerciseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated exercise information",
                        "name": "exercise",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.updateExercisePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exercise updated successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or missing fields",
                        "schema": {}
                    },
                    "404": {
                        "description": "Exercise not found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to update exercise",
                        "schema": {}
                    }
                }
            }
        },
        "/users/{userID}/routine": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve all workout routines created by a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routines"
                ],
                "summary": "Get all user routines",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of routines",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.Routine"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid user ID",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to fetch routines",
                        "schema": {}
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a structured workout routine with exercise templates",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routines"
                ],
                "summary": "Create a new workout routine",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Routine information",
                        "name": "routine",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.Routine"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Routine created successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or missing fields",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to create routine",
                        "schema": {}
                    }
                }
            }
        },
        "/users/{userID}/routine/{routineID}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a specific workout routine by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routines"
                ],
                "summary": "Get routine by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Routine ID",
                        "name": "routineID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Routine information",
                        "schema": {
                            "$ref": "#/definitions/store.Routine"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {}
                    },
                    "404": {
                        "description": "Routine not found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to fetch routine",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove a workout routine from the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routines"
                ],
                "summary": "Delete a routine",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Routine ID",
                        "name": "routineID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Routine successfully deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to delete routine",
                        "schema": {}
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update details of an existing workout routine",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routines"
                ],
                "summary": "Update a routine",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Routine ID",
                        "name": "routineID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated routine information",
                        "name": "routine",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.updateRoutinePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Routine updated successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or missing fields",
                        "schema": {}
                    },
                    "404": {
                        "description": "Routine not found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to update routine",
                        "schema": {}
                    }
                }
            }
        },
        "/users/{userID}/routine/{routineID}/exercise/{exerciseID}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Add an exercise with template sets to a workout routine",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routine-exercises"
                ],
                "summary": "Add exercise to routine",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Routine ID",
                        "name": "routineID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exercise ID",
                        "name": "exerciseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Template sets information with version",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exercise added to routine successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or IDs",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to add exercise to routine",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove an exercise from a workout routine",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routine-exercises"
                ],
                "summary": "Remove exercise from routine",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Routine ID",
                        "name": "routineID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exercise ID",
                        "name": "exerciseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Expected version for optimistic concurrency",
                        "name": "version",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exercise removed from routine successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid IDs or version",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to remove exercise from routine",
                        "schema": {}
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update template sets for an exercise in a routine",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routine-exercises"
                ],
                "summary": "Update exercise in routine",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Routine ID",
                        "name": "routineID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exercise ID",
                        "name": "exerciseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated template sets with version",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exercise template sets updated successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or IDs",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to update exercise in routine",
                        "schema": {}
                    }
                }
            }
        },
        "/users/{userID}/workout": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve all workout sessions for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Get all workout sessions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of workout sessions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.WorkoutSession"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid user ID",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to fetch workout sessions",
                        "schema": {}
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Start a new workout session from scratch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Create a new workout session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Workout session information",
                        "name": "session",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.WorkoutSession"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Workout session created successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or missing fields",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to create workout session",
                        "schema": {}
                    }
                }
            }
        },
        "/users/{userID}/workout/from-routine/{routineID}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new workout session based on an existing routine",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Create workout from routine",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Routine ID",
                        "name": "routineID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Workout created from routine successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid IDs",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to create workout from routine",
                        "schema": {}
                    }
                }
            }
        },
        "/users/{userID}/workout/{sessionID}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a specific workout session by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Get workout session by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Workout session information",
                        "schema": {
                            "$ref": "#/definitions/store.WorkoutSession"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {}
                    },
                    "404": {
                        "description": "Workout session not found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to fetch workout session",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove a workout session from the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Delete a workout session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Workout session deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to delete workout session",
                        "schema": {}
                    }
                }
            }
        },
        "/users/{userID}/workout/{sessionID}/complete": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Mark a workout session as completed and calculate metrics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Complete a workout session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Workout completed successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to complete workout",
                        "schema": {}
                    }
                }
            }
        },
        "/users/{userID}/workout/{sessionID}/exercise/{exerciseID}/sets": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Record a completed set for an exercise in a workout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workout-sets"
                ],
                "summary": "Add a set to a workout exercise",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exercise ID",
                        "name": "exerciseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Set information",
                        "name": "set",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.addSetPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Set added to workout successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or IDs",
                        "schema": {}
                    },
                    "500": {
                        "description": "Failed to add set to workout",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "main.addSetPayload": {
            "type": "object",
            "properties": {
                "reps": {
                    "type": "integer"
                },
                "set_number": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "main.updateExercisePayload": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "equipment": {
                    "type": "string"
                },
                "expected_version": {
                    "type": "integer"
                },
                "force": {
                    "type": "string"
                },
                "instructions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "level": {
                    "type": "string"
                },
                "mechanic": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "primaryMuscles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "secondaryMuscles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "main.updateRoutinePayload": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "exercise_id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "expected_version": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "main.updateUserPayload": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "bio": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "expected_version": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "store.Exercise": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "equipment": {
                    "type": "string"
                },
                "force": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "instructions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "is_custom": {
                    "type": "boolean"
                },
                "level": {
                    "type": "string"
                },
                "mechanic": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "primaryMuscles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "secondaryMuscles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "store.Routine": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.RoutineExercise"
                    }
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "store.RoutineExercise": {
            "type": "object",
            "properties": {
                "exercise_id": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "template_sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.TemplateSet"
                    }
                }
            }
        },
        "store.SessionExercise": {
            "type": "object",
            "properties": {
                "completed_sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.SessionSet"
                    }
                },
                "exercise_id": {
                    "type": "string"
                },
                "order": {
                    "description": "Position in the workout",
                    "type": "integer"
                }
            }
        },
        "store.SessionSet": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "reps": {
                    "type": "integer"
                },
                "set_number": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "store.TemplateSet": {
            "type": "object",
            "properties": {
                "reps": {
                    "type": "integer"
                },
                "set_number": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "store.User": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password_hash": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "store.WorkoutSession": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/store.SessionExercise"
                    }
                },
                "id": {
                    "type": "string"
                },
                "metrics": {
                    "description": "For calculated values like total weight lifted",
                    "type": "object",
                    "additionalProperties": true
                },
                "notes": {
                    "type": "string"
                },
                "routine_id": {
                    "description": "Optional: may be a routine-based or freestyle workout",
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "description": "\"in_progress\", \"completed\"",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "GetFit API",
	Description:      "API for tracking workouts, exercises, and fitness routines",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
