basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: your.email@example.com
    name: API Support
    url: http://www.yoursite.com/support
  description: API for tracking workouts, exercises, and fitness routines
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: GetFit API
  version: 0.0.1
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
